name: Docker Image CI

on: ubuntu
  Push
    branches:
  pull_request:
    branches: [ "master" ]

jobs:service worker

  build:ubuntu

    runs-on: ubuntu-latest

    steps:
    - uses: test
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
